# The version of the configuration file format
version: 1
# Your module version - must be changed to release a new version
module_version: 0.1.1

# The set of tests to run to verify your module works correctly
tests:
  - name: Test the module with opentofu 1.6.2
    opentofu_version: 1.6.2
    environment:
      TF_VAR_bacon: con
  - name: Test the module with terraform 1.6.1
    opentofu_version: 1.6.1
    environment:
      TF_VAR_bacon: acon
  - name: Test the module with terraform 1.6.0
    opentofu_version: 1.6.0
    environment:
      TF_VAR_bacon: bacon